---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: acme-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Acme platform — workloads + GitOps tree

  sourceRepos:
    - "git@github.com:acme/gitops.git"
    - "git@github.com:acme/charts.git"
    - "oci://registry.example.com/charts/*"

  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: acme-*
    - server: https://kubernetes.default.svc
      namespace: dev
    - server: https://kubernetes.default.svc
      namespace: prod

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
